version: "3"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  # todo:
  #   build: todo
  #   working_dir: /app
  #   entrypoint: /app/run.sh
  #   volumes:
  #     - ./todo:/app
  #   ports:
  #     - "8000:${TODO_PORT}"
  #   depends_on:
  #     - db
  #     - redis
  #   links:
  #     - db:db
  #     - redis:redis
  #   environment:
  #     - PORT=${TODO_PORT}
  #     - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
  #     - DEVELOPMENT=${DEVELOPMENT}
  #     - REDIS_HOST=${REDIS_HOST}
  #     - REDIS_PORT=${REDIS_PORT}
